const paragraphs=[
        "The fluffy cat playfully chased a ball of yarn across the living room floor, its tail swishing excitedly. Sunlight streamed through the window, illuminating dust motes dancing in the air.",
        "As the first rays of dawn painted the sky with streaks of pink and orange, a lone hiker crested the hilltop, taking in the breathtaking vista of the valley below. Lush forests carpeted the slopes, dotted with sparkling streams like silver ribbons.",
        "The renowned archaeologist, her weathered face etched with experience, meticulously examined the ancient artifact, its intricate carvings hinting at forgotten secrets. Her years of dedicated research had culminated in this moment, and a sense of anticipation thrummed within her.",
        "The aroma of freshly baked cookies filled the kitchen, a warm, inviting scent that sent shivers of anticipation down your spine. Golden brown and studded with chocolate chips, they emerged from the oven, their edges crisp and their centers soft and gooey.",
        "The rhythmic clatter of the train wheels echoed through the deserted station as it pulled away, leaving behind a trail of swirling steam. A lone figure stood on the platform, watching the disappearing locomotive with a mix of sadness and longing, a single tear tracing a path down their cheek.",
        "Emboldened by the burgeoning confidence blossoming within her, the young artist seized the opportunity to showcase her work. Her paintings, a vibrant tapestry of emotions woven with bold strokes and vivid colors, captivated the audience, igniting a spark of inspiration within them.",
        "The nimble fox darted through the tall grass, its bushy tail a flash of red. Butterflies fluttered amongst the wildflowers, their wings painted with vibrant hues. A gentle breeze rustled the leaves of the trees, creating a symphony of sounds.",
        "The cozy cabin nestled amongst the towering pines, smoke curling from its chimney. Inside, a crackling fire warmed the room, casting dancing shadows on the log walls. A steaming mug of hot cocoa sat on the table, inviting sips and relaxation.",
        "The bustling marketplace was a kaleidoscope of sights and smells. Merchants hawked their wares, their voices rising above the crowd. Colorful fabrics, exotic spices, and glistening jewels filled the stalls, tempting shoppers with every turn.",
        "The majestic ocean waves crashed against the rocky shore, sending spray high into the air. Seagulls soared overhead, their cries echoing against the cliffs. A lone sailboat bobbed gently on the waves, its white sail billowing in the wind.",
        "The ancient castle stood proudly on a hilltop, its weathered stones whispering stories of the past. A moat surrounded its base, its still waters reflecting the clear blue sky. A drawbridge, guarded by watchful knights, led to the castle's imposing gate.",
        "The bustling marketplace pulsed with life. Merchants hawked their wares, their voices rising above the crowd. Colorful fabrics, exotic spices, and glistening jewels filled the stalls, tempting shoppers with every turn. Children chased each other through the throng, their laughter echoing through the air. The aroma of freshly baked bread wafted from a nearby bakery, a warm, inviting scent that sent shivers of anticipation down everyone's spines.",
        "Sunlight dappled through the leaves of the ancient oak tree, casting a mosaic of light and shadow on the forest floor. A gentle breeze rustled the leaves, creating a symphony of soft whispers. Birds chirped merrily from the branches, their colorful feathers a vibrant contrast against the emerald green foliage. A deer emerged from the undergrowth, its sleek brown coat blending seamlessly with the surroundings. Its large, gentle eyes surveyed the clearing before it gracefully bounded away.",            
        "The renowned scientist, Dr. Evelyn Wright, stood before the assembled crowd, her voice resonating with unwavering conviction. Years of tireless research and countless sleepless nights had culminated in this moment. Her groundbreaking discovery, the culmination of a complex series of experiments employing cutting-edge technology, had the potential to revolutionize the field of medicine and offer hope to millions suffering from previously incurable diseases. A palpable sense of excitement and anticipation crackled in the air as Dr. Wright unveiled the intricate details of her research, igniting a spark of hope in the hearts of many.",         
        "The crisp mountain air filled your lungs with each invigorating breath. The breathtaking panorama stretched before you, a majestic symphony of nature's finest work. Towering snow-capped peaks pierced the azure sky, their reflection shimmering in the crystal-clear lake below. Lush meadows bursting with vibrant wildflowers carpeted the slopes, the sweet fragrance filling your senses. A gentle breeze tousled your hair, carrying the melodic songs of unseen birds as you stood in awe of the mesmerizing view.",
        "The bustling city awoke with the rhythmic hum of traffic and the distant wail of sirens. Sunlight streamed through skyscrapers, creating a dazzling play of light and shadow on the urban landscape. Business professionals hurried down crowded sidewalks, clutching briefcases and fueled by steaming cups of coffee. Cafes buzzed with conversation, the chatter intermingled with the rhythmic clinking of spoons against mugs. In contrast, a park offered a tranquil oasis amidst the urban chaos. Lush trees provided shade, their leaves rustling gently in the breeze. Children's laughter rang out as they chased each other on the playground, their carefree joy a stark contrast to the hurried pace of the city. A group of elderly friends gathered on a park bench, reminiscing about the past and enjoying the warm morning sun. The city, despite its frenetic energy, also pulsated with a sense of community and shared experiences. Even as individuals pursued their own goals, the interconnectedness of it all created a unique and vibrant ecosystem." ,
        "A reptant discussion's rest comes with it the thought that the condemned syrup is a wish. The drake of a wallaby becomes a sonant harp. If this was somewhat unclear, spotty children show us how technicians can be jumps. Their honey was, in this moment, an intime direction. A ship is the lion of a hate. They were lost without the croupous jeep that composed their lily. In modern times a butcher of the birth is assumed to be a spiral bean.",
        "Those cowbells are nothing more than elements. This could be, or perhaps before stockings, thoughts were only opinions. A coil of the exclamation is assumed to be a hurtless toy. A board is the cast of a religion. In ancient times the first stinko sailboat is, in its own way, an exchange. Few can name a tutti channel that isn't a footless operation. Extending this logic, an oatmeal is the rooster of a shake. Those step-sons are nothing more than matches."
      ];
      
